### PR TITLE
8280890: Cannot use '-Djava.system.class.loader' with class loader in signed JAR

### PR DESCRIPTION
**Pull request by jerboaa**
Please review this critical fix which fixes a regression introduced with with [JDK-8269039: Disable SHA-1 Signed JARs](https://bugs.openjdk.org/browse/JDK-8269039) which was included in `8u362` (note that `8u352` is not affected as  JDK-8269039 is not there). This should be low-risk as it mainly removes use of `java.util.Calendar` API usage in `DisabledAlgorithmConstraints` which can cause issues with applications that contain `CalendarDataProvider`s in signed jars.

Proposing as critical fix so that we don't regress in that regard in 8u362.

Please review this backport. The changes in `keytool/Main.java` didn't apply. Those aren't critical changes for this patch, so I've omitted them. In addition, the test needed some changes to make it work with JDK 8 (comparing to the 11u version). Used `IOUtils.readAllBytes()` over `InputStream.readAllBytes()` in the custom classloader class, fixed some test lib imports and declared `Throwable` to be thrown in `main` as `ProcessTools.executeProcess` throws `Throwable` over `Exception` in 8u.

Regression test fails prior (current jdk8u tree, without this patch) and passes after the product fix.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8280890](https://bugs.openjdk.org/browse/JDK-8280890): Cannot use '-Djava.system.class.loader' with class loader in signed JAR

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u pull/29/head:pull/29` \
`$ git checkout pull/29`

Update a local copy of the PR: \
`$ git checkout pull/29` \
`$ git pull https://git.openjdk.org/jdk8u pull/29/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 29`

View PR using the GUI difftool: \
`$ git pr show -t 29`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u/pull/29.diff">https://git.openjdk.org/jdk8u/pull/29.diff</a>

</details>

### CODE REVIEW

**Comment by jerboaa** [comment]
@gnu-andrew @martinuy Can you please help review this? Thanks!

**Review by gnu-andrew — COMMENTED** [review]
The keytool changes are from [JDK-8273236](https://bugs.openjdk.org/browse/JDK-8273236), another recent fix relating to this SHA-1 deprecation. If the SHA-1 deprecation itself had been integrated a bit earlier, it might have made 8u362.

I don't think that's critical enough to try and get in at this stage  [*edit*: to clarify, I mean JDK-8273236]. I'll propose it for 8u-dev in the new year with the removals from this patch omitted.

The other changes look sensible. Can you enable actions so that builds & tests are run? Once they look good, I'll approve. Thanks.

**Comment by jerboaa** [comment]
> The keytool changes are from [JDK-8273236](https://bugs.openjdk.org/browse/JDK-8273236), another recent fix relating to this SHA-1 deprecation. If the SHA-1 deprecation itself had been integrated a bit earlier, it might have made 8u362.
> 
> I don't think that's critical enough to try and get in at this stage. I'll propose it for 8u-dev in the new year with the removals from this patch omitted.
> 
> The other changes look sensible. Can you enable actions so that builds & tests are run? Once they look good, I'll approve. Thanks.

OK

**Review by gnu-andrew — APPROVED** [review]
Thanks, I see tests running now at https://github.com/jerboaa/jdk8u/actions/runs/3766931919

**Comment by jerboaa** [comment]
Thanks for the review, labelled the bug `jdk8u-critical-request` now.

**Comment by gnu-andrew** [comment]
> [JDK-8273236](https://bugs.openjdk.org/browse/JDK-8273236)



> Thanks for the review, labelled the bug `jdk8u-critical-request` now.

And approved.

**Pull request closed without merging**
