### PR TITLE
8290832: It is no longer possible to change "user.dir" in the JDK8

### PR DESCRIPTION
**Pull request by mrserb**
This is the request to revert the fix for [JDK-8194154](https://bugs.openjdk.org/browse/JDK-8194154) integrated to the [openjdk8u342](https://github.com/openjdk/jdk8u/commit/5fcfb7acbe340c8347bd47413a36dd0b1e267dc1)

The fix for [JDK-8194154](https://bugs.openjdk.org/browse/JDK-8194154) disabled the possibility to change the "user.dir" property.
Changing the "user.dir" was not recommended from the beginning but it was not forbidden, so there are some old applications that rely on the old behavior. 

For compatibility reasons, it would be good to restore the old behavior.

This PR reverts this commit: https://github.com/openjdk/jdk8u/commit/5fcfb7acbe340c8347bd47413a36dd0b1e267dc1

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290832](https://bugs.openjdk.org/browse/JDK-8290832): It is no longer possible to change "user.dir" in the JDK8

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u pull/14/head:pull/14` \
`$ git checkout pull/14`

Update a local copy of the PR: \
`$ git checkout pull/14` \
`$ git pull https://git.openjdk.org/jdk8u pull/14/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14`

View PR using the GUI difftool: \
`$ git pr show -t 14`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u/pull/14.diff">https://git.openjdk.org/jdk8u/pull/14.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — CHANGES_REQUESTED** [review]
Copyright dates need to be reverted in UnixFileSystem.java and WinNTFileSystem.java. Other than that, lgtm.

**Comment by gnu-andrew** [comment]
> Copyright dates need to be reverted in UnixFileSystem.java and WinNTFileSystem.java. Other than that, lgtm.

Yes, I did wonder why those were omitted myself. It should just be a simple `git revert <id>`, no?

**Comment by gnu-andrew** [comment]
@mrserb can you turn on Actions for this repo? I know we already tested this on 8u-dev but it would be good to get those enabled for any future critical fixes that need to go direct to 8u.

If one of you could review #15 that will need to go in before this so it resolves against the right release.

**Comment by mrserb** [comment]
> > Copyright dates need to be reverted in UnixFileSystem.java and WinNTFileSystem.java. Other than that, lgtm.
> 
> Yes, I did wonder why those were omitted myself. It should just be a simple `git revert <id>`, no?

That dates were changed later, the fix in question changed them to 2018, but now they are 2022 due to other fixes.

**Review by phohensee — APPROVED** [review]
In that case, lgtm.

**Comment by mrserb** [comment]
> @mrserb can you turn on Actions for this repo? I know we already tested this on 8u-dev but it would be good to get those enabled for any future critical fixes that need to go direct to 8u.

I think Github disabled those actions since the changes in this repo rarely happen.

**Comment by mrserb** [comment]
actions executed.

**Review by gnu-andrew — APPROVED** [review]
Ah, right, sorry I should have checked the current state of the files. Both were updated by the security fix JDK-8278356.

I've approved the bug (flipped it to a `jdk8u-critical-fix/yes` to reflect it going direct to 8u, not 8u-dev) and the release bump is in now, so this is good to go.

**Comment by gnu-andrew** [comment]
> actions executed.

Thanks. Strange that it would disable them, I've not heard of that before.

**Pull request closed without merging**
