### PR TITLE
8322750: Test "api/java_awt/interactive/SystemTrayTests.html" failed because A blue ball icon is added outside of the system tray

### PR DESCRIPTION
**Pull request by mrserb**
Hi all,

This pull request contains a backport of commit [5a988a50](https://github.com/openjdk/jdk/commit/5a988a5087d0afbb577c6715fd5e1e44564888cb) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Alexander Zvegintsev on 15 Feb 2024 and was reviewed by Jayathirth D V, Alexander Zuev, Prasanta Sadhukhan and Phil Race.

Backport is not clean, in jdk8u-dev the "sun.desktop" property is used to pass the "desktop name" from native, see
https://bugs.openjdk.org/browse/JDK-8212701.

tck-red-8

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8322750](https://bugs.openjdk.org/browse/JDK-8322750) needs maintainer approval

### Issue
 * [JDK-8322750](https://bugs.openjdk.org/browse/JDK-8322750): Test "api/java_awt/interactive/SystemTrayTests.html" failed because A blue ball icon is added outside of the system tray (**Bug** - P1 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u.git pull/53/head:pull/53` \
`$ git checkout pull/53`

Update a local copy of the PR: \
`$ git checkout pull/53` \
`$ git pull https://git.openjdk.org/jdk8u.git pull/53/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 53`

View PR using the GUI difftool: \
`$ git pr show -t 53`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u/pull/53.diff">https://git.openjdk.org/jdk8u/pull/53.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u/pull/53#issuecomment-1968272965)

### CODE REVIEW

**Comment by mrserb** [comment]
FYI https://github.com/openjdk/jdk8u-dev/pull/458

**Review by phohensee — APPROVED** [review]
Clean backport from 11u.

**Comment by gnu-andrew** [comment]
From the bug:
~~~
Fix request (11u 8u)

Mostly clean backport. The patch is slightly adjusted due to the missing https://bugs.openjdk.org/browse/JDK-8212701 in 8u and 11u.
The fix was verified manually. no new issues were found by the jdk_desktop tests. 
~~~
Would be good to keep everything in one place.

I do find it curious that this is a (critical) issue now. The change turns off the system tray support on GNOME < 45, which implies that is has been broken since GNOME 3 (which introduced gnome-shell that the test relies on) but that it is apparently fix in 45 and up. So it has been broken for years. 

/approve yes

**Pull request closed without merging**
