### PR TITLE
8264728:When use chinese IME, the candidate box isn't moved with caret of JTextArea

### PR DESCRIPTION
**Pull request by quantum6**
JDK-8264728 : When use chinese IME, the candidate box isn't moved with caret of JTextArea
Type: Bug
Component: client-libs
Sub-Component: java.awt:i18n
Affected Version: 8,9,15,16
Priority: P3
Status: Open
Resolution: Unresolved
OS: linux
CPU: x86_64

/signed
/covered

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u pull/31/head:pull/31` \
`$ git checkout pull/31`

Update a local copy of the PR: \
`$ git checkout pull/31` \
`$ git pull https://git.openjdk.org/jdk8u pull/31/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 31`

View PR using the GUI difftool: \
`$ git pr show -t 31`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u/pull/31.diff">https://git.openjdk.org/jdk8u/pull/31.diff</a>

</details>

### CODE REVIEW

**Comment by quantum6** [comment]
I have request OCA for 3 months ago, but still on check.
I really dont' why...

> Hi @quantum6, welcome to this OpenJDK project and thanks for contributing!
> 
> We do not recognize you as [Contributor](https://openjdk.java.net/bylaws#contributor) and need to ensure you have signed the Oracle Contributor Agreement (OCA). If you have not signed the OCA, please follow [the instructions](https://oca.opensource.oracle.com/). Please fill in your GitHub username in the "Username" field of the application. Once you have signed the OCA, please let us know by writing `/signed` in a comment in this pull request.
> 
> If you already are an OpenJDK [Author](https://openjdk.java.net/bylaws#author), [Committer](https://openjdk.java.net/bylaws#committer) or [Reviewer](https://openjdk.java.net/bylaws#reviewer), please click [here](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1) to open a new issue so that we can record that fact. Please use "Add GitHub user quantum6" as summary for the issue.
> 
> If you are contributing this work on behalf of your employer and your employer has signed the OCA, please let us know by writing `/covered` in a comment in this pull request.

**Comment by quantum6** [comment]
It seems that the three problems are caused by other commit.

**Comment by gnu-andrew** [comment]
New changes for 8u should go to https://github.com/openjdk/jdk8u-dev. This tree is for critical regression fixes for the next release only.

**Comment by quantum6** [comment]
Confirmed! Thank you!
Good luck!

**Pull request closed without merging**
