### PR TITLE
8304053: Revert "8303408: [AIX] Broken jdk8u build after JDK-8266391"

### PR DESCRIPTION
**Pull request by sxa**
This reverts commit 4a837299c68071be563e376efe6f12852bc130e7.

After the [AIX build break fix](https://github.com/openjdk/jdk8u/commit/4a837299c68071be563e376efe6f12852bc130e7), a [subsequent commit to fix Solaris](https://github.com/openjdk/jdk8u/commit/ebbd3a87b0c473a744499d5f7691e5207cd73186) caused a duplicate symbol error during compilation on AIX. This should fix it. Verified on [AIX](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-temurin/254/console) and [Solaris/x64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-temurin/290/console)

This PR reverts the AIX fix, leaving the solaris (generic UNIX) fix to apply to both platforms. Opening against jdk8u since this is a build break. Will create an equivalent PR for jdk8u-dev.

Please let me know if there is a specific process required for such revert commits

Original AIX issue: https://bugs.openjdk.org/browse/JDK-8303408 and [8u-dev PR](https://github.com/openjdk/jdk8u-dev/pull/274)
Original Solaris issue: https://bugs.openjdk.org/browse/JDK-8303828 and [8u-dev PR](https://github.com/openjdk/jdk8u-dev/pull/280)
Earlier backport that introduced the original breaks: https://bugs.openjdk.org/browse/JDK-8266391

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304053](https://bugs.openjdk.org/browse/JDK-8304053): Revert "8303408: [AIX] Broken jdk8u build after JDK-8266391"

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u pull/39/head:pull/39` \
`$ git checkout pull/39`

Update a local copy of the PR: \
`$ git checkout pull/39` \
`$ git pull https://git.openjdk.org/jdk8u pull/39/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 39`

View PR using the GUI difftool: \
`$ git pr show -t 39`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u/pull/39.diff">https://git.openjdk.org/jdk8u/pull/39.diff</a>

</details>

### CODE REVIEW

**Comment by sxa** [comment]
@jerboaa @andrew-m-leonard @adamfarley Can one of you create a bug for this please so I can reference it in the title to be able to pass the checks?

**Comment by adamfarley** [comment]
Sure. 1 second.

**Comment by adamfarley** [comment]
https://bugs.openjdk.org/browse/JDK-8304053

**Comment by sxa** [comment]
Title updated

**Comment by jerboaa** [comment]
> Will create an equivalent PR for jdk8u-dev.

No need, thanks! Once integrated the change will get merged into `jdk8u-dev` in due time.

**Comment by jerboaa** [comment]
Please add `/summary 8303828 supersedes fix of 8303408`. Thanks!

**Review by jerboaa — APPROVED** [review]

**Comment by sxa** [comment]
/summary 8303828 fix supersedes fix of 8303408

**Review by jerboaa — CHANGES_REQUESTED** [review]
Hold off on integrating this, please. See https://github.com/openjdk/jdk8u/pull/40#pullrequestreview-1339562332

**Comment by jerboaa** [comment]
This pr is superseded by #40.

**Pull request closed without merging**
