### PR TITLE
8297804: (tz) Update Timezone Data to 2022g

### PR DESCRIPTION
**Pull request by gnu-andrew**
This is a mostly clean backport of the latest tzdata update.

This pull request contains a backport of commit [ce896731](https://github.com/openjdk/jdk/commit/ce896731d38866c2bf99cd49525062e150d94160) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Andrew John Hughes on 7 Dec 2022 and was reviewed by Naoto Sato.

Changes from the {11,13,15,17,19}u and 20 versions:
* `timezone.xml` does not exist in 8u so the addition there is omitted
* In `metaZones.xml`, `America_Mountain` is used instead of `Mexico_Pacific`. This is consistent with [PR27](https://github.com/openjdk/jdk8u/pull/27) on top of which this PR is based (`America/Ciudad_Juarez` splits from `America/Ojinaga`). 8u does not contain definitions for `Mexico_Pacific`.
* The tzdata updates are duplicated in `jdk/test/sun/util/calendar/zi/tzdata`, as currently required for 8u testing.

Tests in `java/util/TimeZone`, `java/time/test`, `sun/util/calendar`, `sun/util/resources` and `sun/text/resources` all pass.  The rearguard changes are identical to those for vanguard, as verified against the rearguard data generated using `make rearguard_tarballs` in the tzdata2022g distribution.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297804](https://bugs.openjdk.org/browse/JDK-8297804): (tz) Update Timezone Data to 2022g

### Reviewers
 * [Dmitry Cherepanov](https://openjdk.org/census#dcherepanov) (@dimitryc - **Reviewer**) ⚠️ Review applies to [ac90f9d7](https://git.openjdk.org/jdk8u/pull/28/files/ac90f9d72787606d5cb298c65ff705596f0d2281)
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**) ⚠️ Review applies to [ac90f9d7](https://git.openjdk.org/jdk8u/pull/28/files/ac90f9d72787606d5cb298c65ff705596f0d2281)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u pull/28/head:pull/28` \
`$ git checkout pull/28`

Update a local copy of the PR: \
`$ git checkout pull/28` \
`$ git pull https://git.openjdk.org/jdk8u pull/28/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 28`

View PR using the GUI difftool: \
`$ git pr show -t 28`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u/pull/28.diff">https://git.openjdk.org/jdk8u/pull/28.diff</a>

</details>

### CODE REVIEW

**Review by dimitryc — APPROVED** [review]
Looks good.

**Review by jerboaa — APPROVED** [review]

**Comment by gnu-andrew** [comment]
Thanks both. Flagged with `jdk8u-critical-request`.

**Comment by gnu-andrew** [comment]
I see `jdk8u-critical-yes`.

/integrate

**Comment by gnu-andrew** [comment]
> @gnu-andrew Please do not rebase or force-push to an active PR as it invalidates existing review comments. Note for future reference, the bots always squash all changes into a single commit automatically as part of the integration. See [OpenJDK Developers’ Guide](https://openjdk.org/guide/#working-with-pull-requests) for more information.

Rebasing is the right thing to do here, as Git will replace the commit from the dependent PR with the one that's been pushed. No point doing unnecessary work merging them.

**Pull request closed without merging**
